;;; queue-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (directory-file-name
                         (or (file-name-directory #$) (car load-path))))



;;; Generated autoloads from queue.el

(defalias 'make-queue 'queue-create "\
Create an empty queue data structure.")
(register-definition-prefixes "queue" '("queue"))

;;; End of scraped data

(provide 'queue-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; coding: utf-8-emacs-unix
;; End:

;;; queue-autoloads.el ends here
